services:
  mysql_db_1:
    image: mysql:8.0
    container_name: mysql_ecommerce_user
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_user
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mysql_db_2:
    image: mysql:8.0
    container_name: my_ecommerce_order
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_order
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql2

  mysql_db_3:
    image: mysql:8.0
    container_name: mysql_ecommerce_inventory
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_inventory
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql3

  mysql_db_4:
    image: mysql:8.0
    container_name: mysql_ecommerce_payment
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_payment
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3311:3306"
    volumes:
      - mysql_data:/var/lib/mysql3

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Configure Kafka as both a broker and a controller (KRaft mode)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'

      # Define internal and external communication listeners
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      # Required cluster settings
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      # CRITICAL SINGLE-NODE SETTINGS
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
      image: provectuslabs/kafka-ui:latest
      container_name: kafka-ui
      ports:
        - "8085:8080"
      depends_on:
        - kafka
      environment:
        KAFKA_CLUSTERS_0_NAME: 'local-cluster'
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:29092'

  redis:
    image: redis:latest
    container_name: redis_ecommerce
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--requirepass root --appendonly yes
    restart: unless-stopped

volumes:
  mysql_data:
  kafka_data:
  redis_data:
