server:
  port: 8086

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3311/ecommerce_payment?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

kafka-topics:
  inventory_reserved_topic: inventory_reserved
  order_purchased_topic: order_purchased
  order_purchase_failed_topic: order_purchase_failed